extends:
  - '@antfu'
  - '@unocss'

rules:
  no-console: [warn, {allow: [warn, error, debug, groupCollapsed, groupEnd]}]
  vue/singleline-html-element-content-newline: off
  jsonc/sort-keys: off
  '@unocss/order': off
  object-property-newline: off
